services:
  app:
    image: felarn/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: dockerfile.production
    command: make test
    depends_on:
      - db

  db:
    image: postgres:latest
    # ports:
    #   - 0.0.0.0:5432:5432
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
