services:
  app:
    image: felarn/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
