services:
  app:
    image: felarn/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: dockerfile.production
    command: make test
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    # ports:
    #   - 0.0.0.0:5432:5432
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      # test: ['CMD-SHELL', 'pg_isready -U postgres']
      test:
        [
          'CMD-SHELL',
          "pg_isready -U postgres -d postgres && psql -U postgres -d postgres -c 'SELECT 1'",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
